# Generated by Django 4.0.3 on 2022-04-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_age', models.IntegerField()),
                ('stu_class', models.CharField(max_length=20)),
                ('sut_dept', models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('eee', 'EEE'), ('mech', 'MECH')], max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
