# Generated by Django 4.0.3 on 2022-04-04 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('staff_count', models.IntegerField()),
                ('hod', models.CharField(max_length=20)),
                ('total_subjects', models.IntegerField()),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_code', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
    ]
