# Generated by Django 4.0.3 on 2022-04-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_department_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
